from __future__ import annotations

from mtplx.constants import DEFAULT_RUNTIME_MODEL_DIR
from mtplx.default_models import DEFAULT_MODEL_ID
from mtplx.profiles import DEFAULT_PROFILE_NAME

from .catalog import SettingCatalog
from .schema import SettingAlias, SettingSpec, SettingType, Visibility


def _setting(
    name: str,
    value_type: SettingType,
    default: object,
    *,
    domain: str,
    config_key: str | None,
    cli: tuple[str, ...] = (),
    env: tuple[str, ...] = (),
    **kwargs: object,
) -> SettingSpec:
    aliases = (
        *((SettingAlias(config_key, "config"),) if config_key else ()),
        *(SettingAlias(value, "cli") for value in cli),
        *(SettingAlias(value, "env") for value in env),
    )
    return SettingSpec(
        name,
        value_type,
        default,
        domain=domain,
        aliases=aliases,
        **kwargs,
    )


BUILTIN_SETTINGS = (
    _setting(
        "model.ref",
        SettingType.STRING,
        DEFAULT_MODEL_ID,
        domain="model",
        config_key="model",
        cli=("model",),
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "model.cache_dir",
        SettingType.STRING,
        str(DEFAULT_RUNTIME_MODEL_DIR),
        domain="model",
        config_key="model_dir",
        cli=("cache-dir",),
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "runtime.profile",
        SettingType.STRING,
        DEFAULT_PROFILE_NAME,
        domain="runtime",
        config_key="profile",
        cli=("profile",),
        choices=(
            "stable",
            "performance-cold",
            "sustained",
            "turbo",
            "exact",
            "max-diagnostic",
        ),
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "runtime.mtp.enabled",
        SettingType.BOOL,
        True,
        domain="runtime",
        config_key=None,
        cli=("mtp", "no-mtp"),
        visibility=Visibility.PUBLIC,
        live_mutable=True,
    ),
    _setting(
        "runtime.mtp.depth",
        SettingType.INT,
        3,
        domain="runtime",
        config_key=None,
        cli=("depth",),
        minimum=1,
        visibility=Visibility.PUBLIC,
        live_mutable=True,
    ),
    _setting(
        "verify.compiled.mode",
        SettingType.STRING,
        "off",
        domain="verify",
        config_key=None,
        env=("MTPLX_COMPILED_VERIFY",),
        choices=("off", "on", "parity", "parity2"),
        visibility=Visibility.EXPERIMENTAL,
    ),
    _setting(
        "verify.nax.enabled",
        SettingType.BOOL,
        False,
        domain="verify",
        config_key=None,
        env=("MTPLX_NAX_VERIFY",),
        visibility=Visibility.EXPERIMENTAL,
    ),
    _setting(
        "attention.gqa_packed_sdpa.enabled",
        SettingType.BOOL,
        False,
        domain="attention",
        config_key=None,
        env=("MTPLX_GQA_PACKED_SDPA",),
        visibility=Visibility.EXPERIMENTAL,
    ),
    _setting(
        "thermal.control",
        SettingType.STRING,
        "",
        domain="thermal",
        config_key="thermal_control",
        cli=("thermal-control",),
    ),
    _setting(
        "memory.kv.quantization",
        SettingType.STRING,
        "",
        domain="memory",
        config_key="paged_kv_quantization",
        cli=("paged-kv-quantization", "paged-kv-quant", "kv-quant"),
        env=("MTPLX_PAGED_KV_QUANT",),
    ),
    _setting(
        "runtime.scheduler.mode",
        SettingType.STRING,
        "serial",
        domain="runtime",
        config_key="scheduler_mode",
        cli=("scheduler-mode",),
        env=("MTPLX_SCHEDULER_MODE",),
    ),
    _setting(
        "runtime.batching.preset",
        SettingType.STRING,
        "latency",
        domain="runtime",
        config_key="batching_preset",
        cli=("batching-preset",),
        env=("MTPLX_BATCHING_PRESET",),
    ),
    _setting(
        "runtime.requests.max_active",
        SettingType.INT,
        0,
        domain="runtime",
        config_key="max_active_requests",
        cli=("max-active-requests",),
        minimum=0,
    ),
    _setting(
        "runtime.batching.decode_max",
        SettingType.INT,
        0,
        domain="runtime",
        config_key="decode_batch_max",
        cli=("decode-batch-max",),
        minimum=0,
    ),
    _setting(
        "runtime.batching.wait_ms",
        SettingType.FLOAT,
        0.0,
        domain="runtime",
        config_key="batch_wait_ms",
        cli=("batch-wait-ms",),
        minimum=0.0,
    ),
    _setting(
        "runtime.prefill.chunk_tokens",
        SettingType.INT,
        0,
        domain="runtime",
        config_key="prefill_chunk_tokens",
        cli=("prefill-chunk-tokens",),
        minimum=0,
    ),
    _setting(
        "runtime.mtp.cohorts.enabled",
        SettingType.BOOL,
        False,
        domain="runtime",
        config_key="experimental_mtp_cohorts",
        cli=("experimental-mtp-cohorts",),
        visibility=Visibility.EXPERIMENTAL,
    ),
    _setting(
        "cache.session.ssd.mode",
        SettingType.STRING,
        "on",
        domain="cache",
        config_key="ssd_session_cache",
        cli=("ssd-session-cache",),
    ),
    _setting(
        "cache.session.ssd.directory",
        SettingType.STRING,
        "",
        domain="cache",
        config_key="ssd_session_cache_dir",
        cli=("ssd-session-cache-dir",),
    ),
    _setting(
        "cache.session.ssd.max_size",
        SettingType.STRING,
        "100GB",
        domain="cache",
        config_key="ssd_session_cache_max_size",
        cli=("ssd-session-cache-max-size",),
    ),
    _setting(
        "cache.session.ssd.min_prefix_tokens",
        SettingType.INT,
        512,
        domain="cache",
        config_key="ssd_session_cache_min_prefix_tokens",
        cli=("ssd-session-cache-min-prefix-tokens",),
        minimum=0,
    ),
    _setting(
        "cache.session.ram.policy",
        SettingType.STRING,
        "",
        domain="cache",
        config_key="ram_session_cache_policy",
        cli=("ram-session-cache-policy",),
    ),
    _setting(
        "cache.session.ram.max_entries",
        SettingType.INT,
        0,
        domain="cache",
        config_key="ram_session_cache_max_entries",
        cli=("ram-session-cache-max-entries",),
        env=("MTPLX_SESSION_BANK_MAX_ENTRIES",),
        minimum=0,
    ),
    _setting(
        "cache.session.ram.max_size",
        SettingType.STRING,
        "",
        domain="cache",
        config_key="ram_session_cache_max_size",
        cli=("ram-session-cache-max-size",),
        env=("MTPLX_SESSION_BANK_MAX_BYTES",),
    ),
    _setting(
        "cache.session.ram.per_session_max_size",
        SettingType.STRING,
        "",
        domain="cache",
        config_key="ram_session_cache_per_session_max_size",
        cli=("ram-session-cache-per-session-max-size",),
        env=("MTPLX_SESSION_BANK_PER_SESSION_BYTES",),
    ),
    _setting(
        "cache.session.ram.block_prefix_restore",
        SettingType.BOOL,
        True,
        domain="cache",
        config_key="ram_session_block_prefix_restore",
        cli=("ram-session-block-prefix-restore",),
        env=("MTPLX_SESSION_BLOCK_PREFIX_RESTORE",),
    ),
    _setting(
        "model.context_window",
        SettingType.INT,
        0,
        domain="model",
        config_key="context_window",
        cli=("context-window",),
        minimum=0,
    ),
    _setting(
        "generation.reasoning",
        SettingType.STRING,
        "auto",
        domain="generation",
        config_key="reasoning",
        cli=("reasoning",),
        choices=("auto", "on", "off"),
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "generation.reasoning_effort",
        SettingType.STRING,
        "auto",
        domain="generation",
        config_key="reasoning_effort",
        cli=("reasoning-effort",),
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "generation.temperature",
        SettingType.FLOAT,
        0.6,
        domain="generation",
        config_key="temperature",
        cli=("temperature", "default-temperature"),
        minimum=0.0,
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "generation.top_p",
        SettingType.FLOAT,
        0.95,
        domain="generation",
        config_key="top_p",
        cli=("top-p", "default-top-p"),
        minimum=0.0,
        maximum=1.0,
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "generation.top_k",
        SettingType.INT,
        20,
        domain="generation",
        config_key="top_k",
        cli=("top-k", "default-top-k"),
        minimum=0,
        visibility=Visibility.PUBLIC,
    ),
    _setting(
        "server.api_key_file",
        SettingType.STRING,
        "",
        domain="server",
        config_key="api_key_file",
        cli=("api-key-file",),
        secret=True,
    ),
)


def default_setting_catalog() -> SettingCatalog:
    return SettingCatalog(BUILTIN_SETTINGS)
