"""Generated compatibility inventory. Run scripts/audit_settings_catalog.py."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LegacyEnvSpec:
    domain: str
    visibility: str = "internal"
    lifecycle: str = "compatibility"
    classification: str = "explicit"


INTERNAL_ENV_SPECS: dict[str, LegacyEnvSpec] = {
    "MTPLX_ABLATE_LINEAR_ATTN": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_COMPACT_CONTEXT_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_COMPACT_HEAD_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_COMPACT_MAX_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_COMPACT_TAIL_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_COMPACT_CONTEXT_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_COMPACT_HEAD_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_COMPACT_MAX_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_COMPACT_TAIL_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_COMPACT_THRESHOLD_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_LINE_MAX_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_MIN_LINES_PER_FILE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_MULTI_FILE_LINE_MAX_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_READ_INSPECTION_TOTAL_MAX_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_TOOL_RESULT_COMPACT_HEAD_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_TOOL_RESULT_COMPACT_MAX_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_TOOL_RESULT_COMPACT_TAIL_LINES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_TOOL_RESULT_COMPACT_THRESHOLD_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ACTIVE_TOOL_RESULT_LINE_MAX_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AIME_CLEAR_CACHE_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AIME_PARENT_PID": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AIME_PROCESS_ISOLATION": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AIME_RELEASE_PARENT_RUNTIME": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AIME_WORKER_DRAIN_S": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ALLOW_LONG_CONTEXT_DENSE_FALLBACK": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ALLOW_PAGED_ACTIVE_ARRAY_SNAPSHOT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ALLOW_UNSAFE_LONG_CONTEXT_PREFILL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ALLOW_UNSAFE_PREFILL_STOCK_CACHE_ONLY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_API_KEY": LegacyEnvSpec("server", classification="prefix:SERVER_API"),
    "MTPLX_APP_LAUNCH_ID": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_APP_PARENT_PID": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_APP_SETTINGS_PATH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AR_BATCH_LONG_BURST_PROMPT_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AR_BATCH_LONG_BURST_WAIT_MS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AR_BATCH_SHARED_PREFILL_MIN_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AR_RETURN_HIDDEN": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ASSERT_NO_LARGE_Q_SPLIT_FALLBACK": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_ASSERT_NO_PAGED_ACTIVE_ARRAYS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_AUTH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_BATCH_TARGET_ARRAYS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_BATCH_TARGET_DISTS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_BENCH_TUNE_TELEMETRY": LegacyEnvSpec("benchmark", classification="prefix:BENCH"),
    "MTPLX_BLOCKWISE_ATTN": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_BLOCKWISE_ATTN_THRESHOLD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_BLOCK_OWNED_ATTN_KV": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_BUNDLED_THERMALFORGE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_COMMIT_DETACH_COMPONENTS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_COMMIT_DETACH_CONV_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_COMMIT_DETACH_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_COMMIT_DETACH_GDN_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_COMMIT_DETACH_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_CONTIGUOUS_GDN_STATE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CAPTURE_CUSTOM_KERNEL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CHAT_TEMPLATE_PATH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CHAT_TEMPLATE_PROFILE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CLEAR_CACHE_AFTER_REQUEST": LegacyEnvSpec("cache", classification="prefix:CACHE"),
    "MTPLX_CLEAR_CACHE_EVERY": LegacyEnvSpec("cache", classification="prefix:CACHE"),
    "MTPLX_CLEAR_CACHE_EVERY_CONTEXT_THRESHOLD": LegacyEnvSpec("cache", classification="prefix:CACHE"),
    "MTPLX_CLEAR_CACHE_EVERY_LONG_CONTEXT": LegacyEnvSpec("cache", classification="prefix:CACHE"),
    "MTPLX_CLIENT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_COMPILED_VERIFY_BOUNDARY": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_DONATION": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_FORCE": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_GROWTH_RESERVE": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_MAX_CONTEXT": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_MAX_LEN": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_PREWARM": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_SHARED_TRACES": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_COMPILED_VERIFY_STATS": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_CONFIG": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_CURRENT_PREFILL_CONTEXT_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DEBUG_PREFIX_DIVERGENCE": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_DECODE_TRACE_INTERVAL_S": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DECODE_TRACE_JSONL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DECODE_TRACE_LABEL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DEFAULT_MODEL_VARIANT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DEFER_VERIFY_HIDDEN_EVAL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_ATTN_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_COMPONENTS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_CONV_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_GDN_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_LIVE_OUTPUTS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_LIVE_OUTPUTS_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DETACH_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DIAGNOSTIC_AR_RETURN_HIDDEN": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DRAFT_TEMPERATURE_SCALE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_DROP_EVENTS": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_DYNAMIC_PAGED_KV": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_DYNAMIC_PAGED_KV_MARGIN": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_DYNAMIC_PAGED_KV_MAX_INITIAL_NEW_TOKENS": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_DYNAMIC_PAGED_KV_MIN_BLOCKS": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_DYNAMIC_PAGED_KV_PREVIOUS_HIGH_WATER": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_DYNAMIC_PAGED_KV_TOKENS": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_EVAL_AUDIT": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_EVAL_AUDIT_STDERR": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_EVAL_STATE_ROOTS_INCLUDE_LIVE": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_EVAL_STATE_ROOTS_INCLUDE_MTP": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_EVAL_STATE_ROOTS_ON_COMMIT": LegacyEnvSpec("diagnostics", classification="prefix:TRACE_DEBUG"),
    "MTPLX_EXPORT_VERIFY_DOT_CYCLES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_EXPORT_VERIFY_DOT_DIR": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_EXPORT_VERIFY_DOT_INCLUDE_CACHE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_EXPORT_VERIFY_DOT_INCLUDE_CAPTURES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FAN_MODE": LegacyEnvSpec("thermal", classification="prefix:THERMAL"),
    "MTPLX_FORCE_GPU_FAMILY_FALLBACK": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FORGE_CANCEL_DIR": LegacyEnvSpec("thermal", classification="prefix:FORGE"),
    "MTPLX_FORGE_DISCOVER_RUNTIME": LegacyEnvSpec("thermal", classification="prefix:FORGE"),
    "MTPLX_FORGE_MODEL_ROOT": LegacyEnvSpec("thermal", classification="prefix:FORGE"),
    "MTPLX_FUSED_LOGITS_TOPK": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FUSED_LOGITS_TOPK_TILE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FUSE_ATTN_QKV_PROJECTIONS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FUSE_GDN_NORM_GATE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FUSE_GDN_PROJECTIONS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_FUSE_POST_NORM_RESIDUAL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GDN_BOUNDARY_CAPTURE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GDN_BOUNDARY_MAX": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GDN_BOUNDARY_TAIL_INTERVAL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GDN_OUT_QMV8": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GEMMA4_COMPILE_DISTRIBUTIONS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GEMMA4_COMPILE_VERIFY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GEMMA4_DEFAULT_DEPTH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GEMMA4_EVAL_TARGET_HIDDEN_BEFORE_DISTRIBUTION": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GEMMA4_TARGET_DISTRIBUTIONS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GEMMA4_TARGET_DISTRIBUTION_WINDOW": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GPU_CLOCK_ANCHOR": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GQA_PACKED_SDPA_BLOCKS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GQA_PACKED_SDPA_THRESHOLD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GQA_PACKED_SDPA_TRACE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GRAPHBANK_PAGED_STATIC_MAX_OFFSET": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_GRAPHBANK_PRESERVE_PAGED_KV": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_KERNEL_SELFCHECK": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LATE_DEPTH_AFTER": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LATE_DEPTH_BEFORE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LATE_DEPTH_SWITCH_AFTER_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LAZY_BONUS_VERIFY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LAZY_BONUS_VERIFY_MIN_DEPTH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LAZY_MTP_HISTORY_APPEND": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LAZY_TARGET_DISTRIBUTIONS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LAZY_VERIFY_LOGITS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LINEAR_CONV1D_CAPTURE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LINEAR_GDN_FROM_CONV": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LINEAR_GDN_FROM_CONV_TGY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LONG_CONTEXT_MTP_DEPTH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LONG_CONTEXT_MTP_DEPTH_POLICY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LONG_CONTEXT_MTP_DEPTH_THRESHOLD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_ALLOWED_LENGTH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_ARM_OCCURRENCES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_DISARM_AFTER": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_GROWTH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_MASK_TOOL_CALLS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_MAX_CANDIDATES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_MIN_DISTINCT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_MIN_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_NGRAM": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_PENALTY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_PENALTY_CAP": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_SCAN_INTERVAL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_LOOP_GUARD_WINDOW": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MAX_ACTUAL_RAMP_VERIFIED": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MAX_REQUESTED": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MAX_VERIFIED_AT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MAX_VERIFIED_JSON": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MEMORY_LIMIT_BYTES": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MLP_CALL_VARIANT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MLX_CACHE_LIMIT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MMAP_WORKERS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_MODEL_DIR": LegacyEnvSpec("model", classification="prefix:MODEL"),
    "MTPLX_MTP_HISTORY_LAST_WINDOW": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_HISTORY_LAST_WINDOW_THRESHOLD": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_HISTORY_MATERIALIZE_EVERY": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_HISTORY_POLICY": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_POSITION_BASE": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_POSITION_CAP": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_POSITION_MODE": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_MTP_POSITION_PERIOD": LegacyEnvSpec("runtime", classification="prefix:MTP"),
    "MTPLX_NATIVE_GDN_TAIL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NATIVE_GDN_TAIL_SIMDGROUPS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NATIVE_MLP": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NATIVE_MLP_CONTEXT_THRESHOLD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NATIVE_MLP_MAX_M": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NATIVE_MLP_MIN_M": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NATIVE_MLP_ROWWISE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NAX_M4_IMPL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NO_BANNER": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_NO_COLOR": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OMIT_SPECULATIVE_BONUS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OPENCODE_CONFIG": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_OPENCODE_DESKTOP_APP_SUPPORT": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_OPENCODE_DESKTOP_SETTINGS_STORE": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_OPENCODE_TOOL_HISTORY_LIVE_FRONTIER": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_OPENCODE_TOOL_HISTORY_SESSIONBANK_BYPASS": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_OPTIMIZED_QUALITY_MODEL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OPTIMIZED_SPEED_MODEL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OWNED_ATTN_KV": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OWNED_ATTN_KV_BLOCK_SIZE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OWNED_ATTN_KV_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OWNED_ATTN_KV_STEP": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OWNED_RECURRENT_STATE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_OWNED_RECURRENT_STATE_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_PAGED_ATTENTION_TRACE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_PAGED_GQA_SDPA_ROUTE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_PI_CONVERGENCE_AFTER_TOOLS": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_PI_MODELS_JSON": LegacyEnvSpec("integration", classification="prefix:INTEGRATION"),
    "MTPLX_POSTCOMMIT_WAIT_TIMEOUT_S": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_PREFILL_CHUNK_CACHE_CLEANUP": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_CHUNK_CACHE_CLEANUP_EVERY": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_CHUNK_SIZE": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_CHUNK_SIZE_DENSE": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_CHUNK_SIZE_REPAGE": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_EXTERNAL_EMIT_LOGITS": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_OMLX_EXTERNAL": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_ROUTE_TRACE": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PREFILL_STOCK_CACHE_ONLY": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_PUBLISH_MANIFEST": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_QUICKSTART_STATE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_RATE_LIMIT_PER_MINUTE": LegacyEnvSpec("server", classification="prefix:SERVER_API"),
    "MTPLX_READ_ONLY_INSPECTION_FORCE_ANSWER_AFTER_TOOLS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_REPETITION_STOP_MAX_BLOCK_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_REPETITION_STOP_MIN_BLOCK_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_REPETITION_STOP_MIN_REPEATED_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_REPETITION_STOP_MIN_REPEATS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_REPETITION_STOP_MIN_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SDPA_2PASS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SDPA_2PASS_BLOCKS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SDPA_2PASS_MAX_Q": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SDPA_2PASS_THRESHOLD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SDPA_DYNAMIC_OFFSET_ACTIVE_BLOCKS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SESSIONBANK_LIVE_REFS_FOR_IMPLICIT_SESSIONS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SESSION_BLOCK_PREFIX_MIN_MATCH_TOKENS": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_BOUNDARY_TRUE_RESTORE": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_LAZY_SNAPSHOT": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_LIVE_FRONTIER_REFERENCE_RESTORE": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_NEAR_PREFIX_MAX_TOKEN_GAP": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_NEAR_PREFIX_MIN_MATCH_TOKENS": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_NEAR_PREFIX_RESTORE": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_POSTCOMMIT_MODE": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_PREFIX_BLOCK_SIZE": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_STORE_ON_PREFILL": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SESSION_STORE_ON_PREFILL_MIN_SUFFIX": LegacyEnvSpec("cache", classification="prefix:SESSION"),
    "MTPLX_SHELL_BANNER_SHOWN": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SKIP_VERIFY_SNAPSHOT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SMALL_SUFFIX_FUSED_MAX": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SMC_PATH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SOURCE_QMM_MANY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SOURCE_QMM_MANY_STRICT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SOVEREIGN_PATH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SPLIT_FULL_ATTN": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SPLIT_FULL_ATTN_CHUNK_SIZE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SPLIT_FULL_ATTN_THRESHOLD": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SPLIT_VERIFY_EVAL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SSD_DEFERRED_ENCODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SSD_SESSION_CACHE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SSD_SESSION_CACHE_DIR": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SSD_SESSION_CACHE_MAX_SIZE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SSD_SESSION_CACHE_MIN_PREFIX_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_START_ATTACH_PROBE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_STATE_REBASE_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_STATE_ROOT_EVAL_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_STREAM_INTERVAL": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_SUSTAINED_DENSE_DECODE_MAX_CONTEXT": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_SUSTAINED_PREFILL": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_SUSTAINED_PREFILL_LAYOUT": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_TARGET_EMIT_FULL_PREFILL_LOGITS": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_TARGET_LAYER_EVAL_CONTEXT_THRESHOLD": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_TARGET_LAYER_EVAL_EVERY": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_TARGET_LAYER_EVAL_MAX_Q": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_TARGET_LAYER_EVAL_MODE": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_TARGET_LAYER_EVAL_SCHEDULE": LegacyEnvSpec("runtime", classification="prefix:PREFILL"),
    "MTPLX_THERMALFORGE_DIR": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_THERMALFORGE_PATH": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_TOOL_PROMPT_MODE": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_TOOL_RESULT_COMPACT_HEAD_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_TOOL_RESULT_COMPACT_TAIL_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_TOOL_RESULT_COMPACT_THRESHOLD_CHARS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_TRUNK_CACHE_MATERIALIZE_EVERY": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_TUNE_CANDIDATE_SETTLE_S": LegacyEnvSpec("benchmark", classification="prefix:BENCH"),
    "MTPLX_TUNE_CHILD": LegacyEnvSpec("benchmark", classification="prefix:BENCH"),
    "MTPLX_TUNE_STATE": LegacyEnvSpec("benchmark", classification="prefix:BENCH"),
    "MTPLX_TUNE_TIE_PREFER_DEEPER_WITHIN_PCT": LegacyEnvSpec("benchmark", classification="prefix:BENCH"),
    "MTPLX_UNCAPPED_REPETITION_STOP": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_UNCAPPED_RESPONSE_LEASE_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_UNSAFE_LONG_CONTEXT_PREFILL_GUARD_TOKENS": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_VERIFY_HIDDEN_MODE": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_VERIFY_MLP_FUSED": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_VERIFY_OUTPUT_DEPENDS": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_VERIFY_OUTPUT_DEPENDS_AFTER_TOKENS": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_VERIFY_OUTPUT_DEPENDS_EVERY": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_VERIFY_OUTPUT_DEPENDS_INCLUDE_MTP": LegacyEnvSpec("verify", classification="prefix:VERIFY_COMPILED"),
    "MTPLX_VK_M4_NSG": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_VK_M6_NSG": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_VLLM_METAL_PAGED_ATTN": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_ATTN_2PASS_THRESHOLD": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_ATTN_EXACT_GATHER_INDICES": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_ATTN_EXACT_GATHER_LAST_N": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_ATTN_IMPL": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_ATTN_MAX_Q": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_BLOCK_SIZE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_GQA_SDPA": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_GQA_SDPA_MAX_Q": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_GQA_SDPA_MIN_CONTEXT": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_GQA_SDPA_MIN_Q": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_GQA_SDPA_ROUTE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_KV_QUANT": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_LARGE_Q_CHUNK_SIZE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_LARGE_Q_KV_CHUNK_SIZE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_MTP_ATTN": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_MTP_BLOCK_SIZE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_MTP_NUM_BLOCKS": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_NUM_BLOCKS": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_PARTITIONED_ATTN": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_PARTITION_SIZE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_PARTITION_THRESHOLD": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_SLIDING_WINDOW": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_TURBOQUANT": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_TURBOQUANT_K_QUANT": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_TURBOQUANT_V_QUANT": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_PAGED_USE_PRIMITIVE": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_VLLM_METAL_REPO": LegacyEnvSpec("attention", classification="prefix:VLLM_METAL_PAGED"),
    "MTPLX_WARMUP_BACKGROUND": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_WARMUP_COUNT": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_WARMUP_EXTENDED": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_WARMUP_LADDER": LegacyEnvSpec("internal", classification="explicit"),
    "MTPLX_WIRED_LIMIT_BYTES": LegacyEnvSpec("internal", classification="explicit"),
}

# Existing direct reads are a frozen compatibility boundary. New reads
# must use the resolver or be explicitly reviewed into this inventory.
DIRECT_READ_ALLOWLIST = frozenset(
    {
        ("mtplx/attention_split.py", "MTPLX_BLOCKWISE_ATTN_THRESHOLD"),
        ("mtplx/attention_split.py", "MTPLX_GQA_PACKED_SDPA_THRESHOLD"),
        ("mtplx/attention_split.py", "MTPLX_SDPA_2PASS_MAX_Q"),
        ("mtplx/attention_split.py", "MTPLX_SDPA_2PASS_THRESHOLD"),
        ("mtplx/attention_split.py", "MTPLX_SPLIT_FULL_ATTN_CHUNK_SIZE"),
        ("mtplx/attention_split.py", "MTPLX_SPLIT_FULL_ATTN_THRESHOLD"),
        ("mtplx/attention_split.py", "MTPLX_VLLM_METAL_PAGED_ATTN_EXACT_GATHER_LAST_N"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_ALLOW_LONG_CONTEXT_DENSE_FALLBACK"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_ASSERT_NO_PAGED_ACTIVE_ARRAYS"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_GEMMA4_COMPILE_DISTRIBUTIONS"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_GEMMA4_COMPILE_VERIFY"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_GEMMA4_EVAL_TARGET_HIDDEN_BEFORE_DISTRIBUTION"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_GEMMA4_TARGET_DISTRIBUTIONS"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_GEMMA4_TARGET_DISTRIBUTION_WINDOW"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_PAGED_ATTENTION_TRACE"),
        ("mtplx/backends/gemma4_assistant.py", "MTPLX_VLLM_METAL_PAGED_PARTITION_THRESHOLD"),
        ("mtplx/cache_bank/cold_tier.py", "MTPLX_SSD_DEFERRED_ENCODE"),
        ("mtplx/cache_state.py", "MTPLX_GRAPHBANK_PAGED_STATIC_MAX_OFFSET"),
        ("mtplx/cache_state.py", "MTPLX_OWNED_ATTN_KV"),
        ("mtplx/cache_state.py", "MTPLX_OWNED_ATTN_KV_BLOCK_SIZE"),
        ("mtplx/cache_state.py", "MTPLX_OWNED_ATTN_KV_MODE"),
        ("mtplx/cache_state.py", "MTPLX_OWNED_ATTN_KV_STEP"),
        ("mtplx/cache_state.py", "MTPLX_OWNED_RECURRENT_STATE"),
        ("mtplx/cache_state.py", "MTPLX_OWNED_RECURRENT_STATE_MODE"),
        ("mtplx/cache_state.py", "MTPLX_PAGED_GQA_SDPA_ROUTE"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_ATTN"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_ATTN_2PASS_THRESHOLD"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_ATTN_IMPL"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_ATTN_MAX_Q"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_BLOCK_SIZE"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_GQA_SDPA_ROUTE"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_MTP_ATTN"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_MTP_BLOCK_SIZE"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_MTP_NUM_BLOCKS"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_NUM_BLOCKS"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_PARTITION_SIZE"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_PAGED_SLIDING_WINDOW"),
        ("mtplx/cache_state.py", "MTPLX_VLLM_METAL_REPO"),
        ("mtplx/cli.py", "MTPLX_NO_BANNER"),
        ("mtplx/cli.py", "MTPLX_NO_COLOR"),
        ("mtplx/cli.py", "MTPLX_SHELL_BANNER_SHOWN"),
        ("mtplx/cli.py", "MTPLX_SMC_PATH"),
        ("mtplx/cli.py", "MTPLX_SOVEREIGN_PATH"),
        ("mtplx/commands/forge.py", "MTPLX_FORGE_CANCEL_DIR"),
        ("mtplx/commands/forge.py", "MTPLX_FORGE_DISCOVER_RUNTIME"),
        ("mtplx/commands/forge.py", "MTPLX_FORGE_MODEL_ROOT"),
        ("mtplx/commands/forge.py", "MTPLX_MODEL_DIR"),
        ("mtplx/commands/public.py", "MTPLX_API_KEY"),
        ("mtplx/commands/public.py", "MTPLX_DROP_EVENTS"),
        ("mtplx/commands/public.py", "MTPLX_TUNE_STATE"),
        ("mtplx/config.py", "MTPLX_CONFIG"),
        ("mtplx/diagnostics.py", "MTPLX_MODEL_DIR"),
        ("mtplx/engine_session.py", "MTPLX_POSTCOMMIT_WAIT_TIMEOUT_S"),
        ("mtplx/engine_session.py", "MTPLX_SESSION_BANK_MAX_BYTES"),
        ("mtplx/engine_session.py", "MTPLX_SESSION_BANK_MAX_ENTRIES"),
        ("mtplx/engine_session.py", "MTPLX_SESSION_BANK_PER_SESSION_BYTES"),
        ("mtplx/engine_session.py", "MTPLX_SESSION_BLOCK_PREFIX_RESTORE"),
        ("mtplx/gdn_capture.py", "MTPLX_ABLATE_LINEAR_ATTN"),
        ("mtplx/gdn_capture.py", "MTPLX_CAPTURE_CUSTOM_KERNEL"),
        ("mtplx/gdn_capture.py", "MTPLX_FUSE_GDN_NORM_GATE"),
        ("mtplx/gdn_capture.py", "MTPLX_FUSE_GDN_PROJECTIONS"),
        ("mtplx/gdn_capture.py", "MTPLX_FUSE_POST_NORM_RESIDUAL"),
        ("mtplx/gdn_capture.py", "MTPLX_GDN_OUT_QMV8"),
        ("mtplx/gdn_capture.py", "MTPLX_LINEAR_GDN_FROM_CONV"),
        ("mtplx/gdn_capture.py", "MTPLX_LINEAR_GDN_FROM_CONV_TGY"),
        ("mtplx/gdn_capture.py", "MTPLX_NATIVE_GDN_TAIL"),
        ("mtplx/gdn_capture.py", "MTPLX_NATIVE_GDN_TAIL_SIMDGROUPS"),
        ("mtplx/gdn_capture.py", "MTPLX_TARGET_LAYER_EVAL_CONTEXT_THRESHOLD"),
        ("mtplx/gdn_capture.py", "MTPLX_TARGET_LAYER_EVAL_EVERY"),
        ("mtplx/gdn_capture.py", "MTPLX_TARGET_LAYER_EVAL_MAX_Q"),
        ("mtplx/gdn_capture.py", "MTPLX_TARGET_LAYER_EVAL_SCHEDULE"),
        ("mtplx/generation.py", "MTPLX_BATCH_TARGET_ARRAYS"),
        ("mtplx/generation.py", "MTPLX_BATCH_TARGET_DISTS"),
        ("mtplx/generation.py", "MTPLX_BLOCK_OWNED_ATTN_KV"),
        ("mtplx/generation.py", "MTPLX_CAPTURE_COMMIT_DETACH_COMPONENTS"),
        ("mtplx/generation.py", "MTPLX_CAPTURE_COMMIT_DETACH_CONV_EVERY"),
        ("mtplx/generation.py", "MTPLX_CAPTURE_COMMIT_DETACH_EVERY"),
        ("mtplx/generation.py", "MTPLX_CAPTURE_COMMIT_DETACH_GDN_EVERY"),
        ("mtplx/generation.py", "MTPLX_CAPTURE_COMMIT_DETACH_MODE"),
        ("mtplx/generation.py", "MTPLX_CLEAR_CACHE_EVERY"),
        ("mtplx/generation.py", "MTPLX_CURRENT_PREFILL_CONTEXT_TOKENS"),
        ("mtplx/generation.py", "MTPLX_DECODE_TRACE_INTERVAL_S"),
        ("mtplx/generation.py", "MTPLX_DECODE_TRACE_JSONL"),
        ("mtplx/generation.py", "MTPLX_DECODE_TRACE_LABEL"),
        ("mtplx/generation.py", "MTPLX_DEFER_VERIFY_HIDDEN_EVAL"),
        ("mtplx/generation.py", "MTPLX_DETACH_ATTN_EVERY"),
        ("mtplx/generation.py", "MTPLX_DETACH_COMPONENTS"),
        ("mtplx/generation.py", "MTPLX_DETACH_CONV_EVERY"),
        ("mtplx/generation.py", "MTPLX_DETACH_EVERY"),
        ("mtplx/generation.py", "MTPLX_DETACH_GDN_EVERY"),
        ("mtplx/generation.py", "MTPLX_DETACH_LIVE_OUTPUTS"),
        ("mtplx/generation.py", "MTPLX_DETACH_LIVE_OUTPUTS_MODE"),
        ("mtplx/generation.py", "MTPLX_DETACH_MODE"),
        ("mtplx/generation.py", "MTPLX_DRAFT_TEMPERATURE_SCALE"),
        ("mtplx/generation.py", "MTPLX_EVAL_AUDIT"),
        ("mtplx/generation.py", "MTPLX_EVAL_AUDIT_STDERR"),
        ("mtplx/generation.py", "MTPLX_EVAL_STATE_ROOTS_INCLUDE_LIVE"),
        ("mtplx/generation.py", "MTPLX_EVAL_STATE_ROOTS_INCLUDE_MTP"),
        ("mtplx/generation.py", "MTPLX_EVAL_STATE_ROOTS_ON_COMMIT"),
        ("mtplx/generation.py", "MTPLX_GDN_BOUNDARY_CAPTURE"),
        ("mtplx/generation.py", "MTPLX_GDN_BOUNDARY_MAX"),
        ("mtplx/generation.py", "MTPLX_GDN_BOUNDARY_TAIL_INTERVAL"),
        ("mtplx/generation.py", "MTPLX_LATE_DEPTH_AFTER"),
        ("mtplx/generation.py", "MTPLX_LATE_DEPTH_BEFORE"),
        ("mtplx/generation.py", "MTPLX_LATE_DEPTH_SWITCH_AFTER_TOKENS"),
        ("mtplx/generation.py", "MTPLX_LAZY_BONUS_VERIFY_MIN_DEPTH"),
        ("mtplx/generation.py", "MTPLX_MTP_HISTORY_MATERIALIZE_EVERY"),
        ("mtplx/generation.py", "MTPLX_MTP_HISTORY_POLICY"),
        ("mtplx/generation.py", "MTPLX_MTP_POSITION_BASE"),
        ("mtplx/generation.py", "MTPLX_MTP_POSITION_CAP"),
        ("mtplx/generation.py", "MTPLX_MTP_POSITION_MODE"),
        ("mtplx/generation.py", "MTPLX_MTP_POSITION_PERIOD"),
        ("mtplx/generation.py", "MTPLX_OWNED_ATTN_KV"),
        ("mtplx/generation.py", "MTPLX_PAGED_KV_QUANT"),
        ("mtplx/generation.py", "MTPLX_PREFILL_CHUNK_CACHE_CLEANUP_EVERY"),
        ("mtplx/generation.py", "MTPLX_PREFILL_CHUNK_SIZE"),
        ("mtplx/generation.py", "MTPLX_SESSION_BLOCK_PREFIX_RESTORE"),
        ("mtplx/generation.py", "MTPLX_SESSION_STORE_ON_PREFILL"),
        ("mtplx/generation.py", "MTPLX_SESSION_STORE_ON_PREFILL_MIN_SUFFIX"),
        ("mtplx/generation.py", "MTPLX_SMALL_SUFFIX_FUSED_MAX"),
        ("mtplx/generation.py", "MTPLX_STATE_REBASE_EVERY"),
        ("mtplx/generation.py", "MTPLX_SUSTAINED_PREFILL_LAYOUT"),
        ("mtplx/generation.py", "MTPLX_TRUNK_CACHE_MATERIALIZE_EVERY"),
        ("mtplx/generation.py", "MTPLX_UNSAFE_LONG_CONTEXT_PREFILL_GUARD_TOKENS"),
        ("mtplx/generation.py", "MTPLX_VERIFY_HIDDEN_MODE"),
        ("mtplx/generation.py", "MTPLX_VLLM_METAL_PAGED_ATTN"),
        ("mtplx/generation.py", "MTPLX_VLLM_METAL_PAGED_KV_QUANT"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY_BOUNDARY"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY_DONATION"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY_GROWTH_RESERVE"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY_MAX_CONTEXT"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY_MAX_LEN"),
        ("mtplx/graphbank.py", "MTPLX_COMPILED_VERIFY_PREWARM"),
        ("mtplx/graphbank.py", "MTPLX_VLLM_METAL_PAGED_ATTN_MAX_Q"),
        ("mtplx/hf_loader.py", "MTPLX_MODEL_DIR"),
        ("mtplx/kernel_selfcheck.py", "MTPLX_KERNEL_SELFCHECK"),
        ("mtplx/kernels/logits_topk.py", "MTPLX_FUSED_LOGITS_TOPK_TILE"),
        ("mtplx/kernels/sdpa_2pass.py", "MTPLX_SDPA_2PASS_BLOCKS"),
        ("mtplx/kernels/sdpa_gqa_packed.py", "MTPLX_GQA_PACKED_SDPA_BLOCKS"),
        ("mtplx/kv_quant.py", "MTPLX_PAGED_KV_QUANT"),
        ("mtplx/kv_quant.py", "MTPLX_VLLM_METAL_PAGED_KV_QUANT"),
        ("mtplx/loop_guard.py", "MTPLX_LOOP_GUARD"),
        ("mtplx/loop_guard.py", "MTPLX_LOOP_GUARD_MASK_TOOL_CALLS"),
        ("mtplx/models/expert_mlx.py", "MTPLX_MMAP_WORKERS"),
        ("mtplx/mtp_patch.py", "MTPLX_VLLM_METAL_PAGED_MTP_ATTN"),
        ("mtplx/native_mlp.py", "MTPLX_MLP_CALL_VARIANT"),
        ("mtplx/nax_verify.py", "MTPLX_FORCE_GPU_FAMILY_FALLBACK"),
        ("mtplx/nax_verify.py", "MTPLX_NAX_M4_IMPL"),
        ("mtplx/nax_verify.py", "MTPLX_NAX_VERIFY"),
        ("mtplx/opencode.py", "MTPLX_OPENCODE_CONFIG"),
        ("mtplx/opencode.py", "MTPLX_OPENCODE_DESKTOP_APP_SUPPORT"),
        ("mtplx/opencode.py", "MTPLX_OPENCODE_DESKTOP_SETTINGS_STORE"),
        ("mtplx/pi.py", "MTPLX_PI_MODELS_JSON"),
        ("mtplx/prefill_bench.py", "MTPLX_BATCH_TARGET_ARRAYS"),
        ("mtplx/prefill_bench.py", "MTPLX_CLEAR_CACHE_EVERY"),
        ("mtplx/prefill_bench.py", "MTPLX_DEFER_VERIFY_HIDDEN_EVAL"),
        ("mtplx/prefill_bench.py", "MTPLX_MTP_HISTORY_LAST_WINDOW"),
        ("mtplx/prefill_bench.py", "MTPLX_MTP_HISTORY_POLICY"),
        ("mtplx/prefill_bench.py", "MTPLX_PREFILL_CHUNK_CACHE_CLEANUP"),
        ("mtplx/prefill_bench.py", "MTPLX_PREFILL_CHUNK_CACHE_CLEANUP_EVERY"),
        ("mtplx/prefill_bench.py", "MTPLX_PREFILL_CHUNK_SIZE"),
        ("mtplx/prefill_bench.py", "MTPLX_PREFILL_STOCK_CACHE_ONLY"),
        ("mtplx/prefill_bench.py", "MTPLX_SUSTAINED_PREFILL_LAYOUT"),
        ("mtplx/prefill_bench.py", "MTPLX_VERIFY_HIDDEN_MODE"),
        ("mtplx/prefill_bench.py", "MTPLX_VLLM_METAL_PAGED_ATTN_IMPL"),
        ("mtplx/server/openai.py", "MTPLX_AIME_CLEAR_CACHE_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_AIME_PARENT_PID"),
        ("mtplx/server/openai.py", "MTPLX_AIME_PROCESS_ISOLATION"),
        ("mtplx/server/openai.py", "MTPLX_AIME_RELEASE_PARENT_RUNTIME"),
        ("mtplx/server/openai.py", "MTPLX_AIME_WORKER_DRAIN_S"),
        ("mtplx/server/openai.py", "MTPLX_APP_LAUNCH_ID"),
        ("mtplx/server/openai.py", "MTPLX_AR_BATCH_LONG_BURST_PROMPT_TOKENS"),
        ("mtplx/server/openai.py", "MTPLX_AR_BATCH_LONG_BURST_WAIT_MS"),
        ("mtplx/server/openai.py", "MTPLX_AR_BATCH_SHARED_PREFILL_MIN_TOKENS"),
        ("mtplx/server/openai.py", "MTPLX_BATCHING_PRESET"),
        ("mtplx/server/openai.py", "MTPLX_BLOCKWISE_ATTN"),
        ("mtplx/server/openai.py", "MTPLX_BLOCKWISE_ATTN_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_CAPTURE_COMMIT_DETACH_COMPONENTS"),
        ("mtplx/server/openai.py", "MTPLX_CAPTURE_COMMIT_DETACH_CONV_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_CAPTURE_COMMIT_DETACH_GDN_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_CAPTURE_COMMIT_DETACH_MODE"),
        ("mtplx/server/openai.py", "MTPLX_CHAT_TEMPLATE_PATH"),
        ("mtplx/server/openai.py", "MTPLX_CHAT_TEMPLATE_PROFILE"),
        ("mtplx/server/openai.py", "MTPLX_CLEAR_CACHE_AFTER_REQUEST"),
        ("mtplx/server/openai.py", "MTPLX_CLEAR_CACHE_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_CLIENT"),
        ("mtplx/server/openai.py", "MTPLX_DEFER_VERIFY_HIDDEN_EVAL"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_ATTN_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_COMPONENTS"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_CONV_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_GDN_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_LIVE_OUTPUTS"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_LIVE_OUTPUTS_MODE"),
        ("mtplx/server/openai.py", "MTPLX_DETACH_MODE"),
        ("mtplx/server/openai.py", "MTPLX_DYNAMIC_PAGED_KV_MAX_INITIAL_NEW_TOKENS"),
        ("mtplx/server/openai.py", "MTPLX_EVAL_STATE_ROOTS_INCLUDE_LIVE"),
        ("mtplx/server/openai.py", "MTPLX_EVAL_STATE_ROOTS_INCLUDE_MTP"),
        ("mtplx/server/openai.py", "MTPLX_EVAL_STATE_ROOTS_ON_COMMIT"),
        ("mtplx/server/openai.py", "MTPLX_FAN_MODE"),
        ("mtplx/server/openai.py", "MTPLX_GEMMA4_DEFAULT_DEPTH"),
        ("mtplx/server/openai.py", "MTPLX_LATE_DEPTH_AFTER"),
        ("mtplx/server/openai.py", "MTPLX_LATE_DEPTH_BEFORE"),
        ("mtplx/server/openai.py", "MTPLX_LATE_DEPTH_SWITCH_AFTER_TOKENS"),
        ("mtplx/server/openai.py", "MTPLX_LONG_CONTEXT_MTP_DEPTH"),
        ("mtplx/server/openai.py", "MTPLX_LONG_CONTEXT_MTP_DEPTH_POLICY"),
        ("mtplx/server/openai.py", "MTPLX_LONG_CONTEXT_MTP_DEPTH_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_LOOP_GUARD"),
        ("mtplx/server/openai.py", "MTPLX_MAX_ACTUAL_RAMP_VERIFIED"),
        ("mtplx/server/openai.py", "MTPLX_MAX_REQUESTED"),
        ("mtplx/server/openai.py", "MTPLX_MAX_VERIFIED_AT"),
        ("mtplx/server/openai.py", "MTPLX_MEMORY_LIMIT_BYTES"),
        ("mtplx/server/openai.py", "MTPLX_MLP_CALL_VARIANT"),
        ("mtplx/server/openai.py", "MTPLX_MLX_CACHE_LIMIT"),
        ("mtplx/server/openai.py", "MTPLX_MTP_HISTORY_MATERIALIZE_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_MTP_POSITION_BASE"),
        ("mtplx/server/openai.py", "MTPLX_MTP_POSITION_CAP"),
        ("mtplx/server/openai.py", "MTPLX_MTP_POSITION_MODE"),
        ("mtplx/server/openai.py", "MTPLX_MTP_POSITION_PERIOD"),
        ("mtplx/server/openai.py", "MTPLX_NATIVE_GDN_TAIL"),
        ("mtplx/server/openai.py", "MTPLX_NATIVE_GDN_TAIL_SIMDGROUPS"),
        ("mtplx/server/openai.py", "MTPLX_NATIVE_MLP_CONTEXT_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_NATIVE_MLP_MAX_M"),
        ("mtplx/server/openai.py", "MTPLX_NATIVE_MLP_MIN_M"),
        ("mtplx/server/openai.py", "MTPLX_NATIVE_MLP_ROWWISE"),
        ("mtplx/server/openai.py", "MTPLX_OWNED_ATTN_KV"),
        ("mtplx/server/openai.py", "MTPLX_OWNED_ATTN_KV_BLOCK_SIZE"),
        ("mtplx/server/openai.py", "MTPLX_OWNED_ATTN_KV_MODE"),
        ("mtplx/server/openai.py", "MTPLX_OWNED_ATTN_KV_STEP"),
        ("mtplx/server/openai.py", "MTPLX_OWNED_RECURRENT_STATE"),
        ("mtplx/server/openai.py", "MTPLX_OWNED_RECURRENT_STATE_MODE"),
        ("mtplx/server/openai.py", "MTPLX_PAGED_KV_QUANT"),
        ("mtplx/server/openai.py", "MTPLX_SCHEDULER_MODE"),
        ("mtplx/server/openai.py", "MTPLX_SDPA_2PASS"),
        ("mtplx/server/openai.py", "MTPLX_SDPA_2PASS_MAX_Q"),
        ("mtplx/server/openai.py", "MTPLX_SDPA_2PASS_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_SESSIONBANK_LIVE_REFS_FOR_IMPLICIT_SESSIONS"),
        ("mtplx/server/openai.py", "MTPLX_SESSION_BANK_MAX_BYTES"),
        ("mtplx/server/openai.py", "MTPLX_SESSION_BANK_MAX_ENTRIES"),
        ("mtplx/server/openai.py", "MTPLX_SESSION_BANK_PER_SESSION_BYTES"),
        ("mtplx/server/openai.py", "MTPLX_SESSION_POSTCOMMIT_MODE"),
        ("mtplx/server/openai.py", "MTPLX_SPLIT_FULL_ATTN"),
        ("mtplx/server/openai.py", "MTPLX_SPLIT_FULL_ATTN_CHUNK_SIZE"),
        ("mtplx/server/openai.py", "MTPLX_SPLIT_FULL_ATTN_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_SPLIT_VERIFY_EVAL"),
        ("mtplx/server/openai.py", "MTPLX_SSD_SESSION_CACHE"),
        ("mtplx/server/openai.py", "MTPLX_SSD_SESSION_CACHE_DIR"),
        ("mtplx/server/openai.py", "MTPLX_SSD_SESSION_CACHE_MAX_SIZE"),
        ("mtplx/server/openai.py", "MTPLX_STATE_REBASE_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_TARGET_LAYER_EVAL_CONTEXT_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_TARGET_LAYER_EVAL_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_TARGET_LAYER_EVAL_MAX_Q"),
        ("mtplx/server/openai.py", "MTPLX_TARGET_LAYER_EVAL_SCHEDULE"),
        ("mtplx/server/openai.py", "MTPLX_TOOL_PROMPT_MODE"),
        ("mtplx/server/openai.py", "MTPLX_TRUNK_CACHE_MATERIALIZE_EVERY"),
        ("mtplx/server/openai.py", "MTPLX_UNCAPPED_REPETITION_STOP"),
        ("mtplx/server/openai.py", "MTPLX_UNCAPPED_RESPONSE_LEASE_TOKENS"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_ATTN"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_BLOCK_SIZE"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_KV_QUANT"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_MTP_ATTN"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_MTP_BLOCK_SIZE"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_MTP_NUM_BLOCKS"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_NUM_BLOCKS"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_PARTITIONED_ATTN"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_PARTITION_SIZE"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_PARTITION_THRESHOLD"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_SLIDING_WINDOW"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_TURBOQUANT"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_TURBOQUANT_K_QUANT"),
        ("mtplx/server/openai.py", "MTPLX_VLLM_METAL_PAGED_TURBOQUANT_V_QUANT"),
        ("mtplx/server/openai.py", "MTPLX_WARMUP_BACKGROUND"),
        ("mtplx/server/openai.py", "MTPLX_WARMUP_EXTENDED"),
        ("mtplx/server/openai.py", "MTPLX_WARMUP_LADDER"),
        ("mtplx/server/openai.py", "MTPLX_WIRED_LIMIT_BYTES"),
        ("mtplx/session_bank.py", "MTPLX_SESSION_BLOCK_PREFIX_RESTORE"),
        ("mtplx/session_bank.py", "MTPLX_SESSION_BOUNDARY_TRUE_RESTORE"),
        ("mtplx/session_bank.py", "MTPLX_SESSION_LAZY_SNAPSHOT"),
        ("mtplx/session_bank.py", "MTPLX_SESSION_NEAR_PREFIX_MAX_TOKEN_GAP"),
        ("mtplx/thermal.py", "MTPLX_GPU_CLOCK_ANCHOR"),
        ("mtplx/turboquant.py", "MTPLX_VLLM_METAL_PAGED_TURBOQUANT_K_QUANT"),
        ("mtplx/turboquant.py", "MTPLX_VLLM_METAL_PAGED_TURBOQUANT_V_QUANT"),
        ("mtplx/ui/banner.py", "MTPLX_NO_BANNER"),
        ("mtplx/ui/banner.py", "MTPLX_SHELL_BANNER_SHOWN"),
        ("mtplx/ui/onboarding.py", "MTPLX_QUICKSTART_STATE"),
        ("mtplx/verify_kernels.py", "MTPLX_VK_M4_NSG"),
        ("mtplx/verify_kernels.py", "MTPLX_VK_M6_NSG"),
    }
)
