#!/usr/bin/env python3
"""Generate public settings Markdown and JSON from the canonical catalog."""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

MARKDOWN_PATH = REPO_ROOT / "docs" / "reference" / "settings.md"
JSON_PATH = REPO_ROOT / "docs" / "reference" / "settings.json"
MIGRATION_PATH = REPO_ROOT / "docs" / "migration-settings.md"
ALIAS_BEGIN = "<!-- BEGIN GENERATED SETTINGS ALIASES -->"
ALIAS_END = "<!-- END GENERATED SETTINGS ALIASES -->"


def _setting_payload(spec: Any) -> dict[str, Any]:
    aliases = [
        {
            "name": alias.name,
            "source": alias.source,
            "replacement": alias.replacement,
        }
        for alias in sorted(spec.aliases, key=lambda item: (item.source, item.name))
    ]
    return {
        "name": spec.name,
        "domain": spec.domain,
        "type": spec.value_type.value,
        "default": "[redacted]" if spec.secret else spec.default,
        "description": spec.description,
        "visibility": spec.visibility.value,
        "lifecycle": spec.lifecycle.value,
        "live_mutable": spec.live_mutable,
        "restart_behavior": "live" if spec.live_mutable else "restart required",
        "choices": list(spec.choices),
        "minimum": spec.minimum,
        "maximum": spec.maximum,
        "aliases": aliases,
    }


def _markdown_value(value: Any) -> str:
    if value == "":
        return "empty"
    return f"`{json.dumps(value, ensure_ascii=False)}`"


def render_reference() -> tuple[str, dict[str, Any]]:
    from mtplx.settings.builtins import default_setting_catalog

    specs = default_setting_catalog().list()
    settings = [
        _setting_payload(spec)
        for spec in specs
        if spec.visibility.value != "internal"
    ]
    payload = {
        "schema_version": 1,
        "settings": settings,
    }
    by_domain: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in settings:
        by_domain[item["domain"]].append(item)
    lines = [
        "# Canonical Settings Reference",
        "",
        "<!-- Generated by scripts/generate_settings_reference.py. -->",
        "",
        "Use `mtplx settings explain NAME` to inspect the effective value and source.",
        "Secret values are never emitted; secret-file settings show `[redacted]`.",
        "",
    ]
    for domain in sorted(by_domain):
        lines.extend(
            [
                f"## {domain}",
                "",
                "| Setting | Type | Default | Visibility | Lifecycle | Apply | Legacy aliases | Description |",
                "|---|---|---|---|---|---|---|---|",
            ]
        )
        for item in by_domain[domain]:
            aliases = "<br>".join(
                f"`{alias['source']}:{alias['name']}`"
                for alias in item["aliases"]
            ) or "—"
            description = str(item["description"] or "—").replace("|", "\\|")
            lines.append(
                "| "
                + " | ".join(
                    (
                        f"`{item['name']}`",
                        item["type"],
                        _markdown_value(item["default"]),
                        item["visibility"],
                        item["lifecycle"],
                        item["restart_behavior"],
                        aliases,
                        description,
                    )
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines), payload


def render_alias_tables() -> str:
    from mtplx.settings.builtins import default_setting_catalog

    rows: dict[str, list[tuple[str, str]]] = {"cli": [], "env": []}
    for spec in default_setting_catalog().list():
        for alias in spec.aliases:
            if alias.source in rows:
                rows[alias.source].append((alias.name, spec.name))
    lines: list[str] = []
    for source, title in (("cli", "CLI flag aliases"), ("env", "Environment aliases")):
        lines.extend(
            [
                f"## {title}",
                "",
                "| Compatibility name | Canonical setting |",
                "|---|---|",
            ]
        )
        for alias, canonical in sorted(rows[source]):
            rendered = f"--{alias}" if source == "cli" else alias
            lines.append(f"| `{rendered}` | `{canonical}` |")
        lines.append("")
    return "\n".join(lines).rstrip()


def _render_migration(current: str) -> str:
    if ALIAS_BEGIN not in current or ALIAS_END not in current:
        raise ValueError(f"{MIGRATION_PATH}: missing generated alias markers")
    before, remainder = current.split(ALIAS_BEGIN, 1)
    _, after = remainder.split(ALIAS_END, 1)
    return (
        before
        + ALIAS_BEGIN
        + "\n\n"
        + render_alias_tables()
        + "\n\n"
        + ALIAS_END
        + after
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    markdown, payload = render_reference()
    json_text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    migration_current = (
        MIGRATION_PATH.read_text(encoding="utf-8") if MIGRATION_PATH.exists() else None
    )
    migration_expected = (
        _render_migration(migration_current) if migration_current is not None else None
    )
    if args.write:
        MARKDOWN_PATH.parent.mkdir(parents=True, exist_ok=True)
        MARKDOWN_PATH.write_text(markdown, encoding="utf-8")
        JSON_PATH.write_text(json_text, encoding="utf-8")
        if migration_expected is not None:
            MIGRATION_PATH.write_text(migration_expected, encoding="utf-8")
        print(f"wrote {MARKDOWN_PATH} and {JSON_PATH}")
        return 0
    stale = (
        not MARKDOWN_PATH.exists()
        or MARKDOWN_PATH.read_text(encoding="utf-8") != markdown
        or not JSON_PATH.exists()
        or JSON_PATH.read_text(encoding="utf-8") != json_text
        or (
            migration_expected is not None
            and migration_current != migration_expected
        )
    )
    if stale:
        print("error: stale generated settings reference")
        return 1
    print(f"settings reference ok: {len(payload['settings'])} settings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
